### ISSUE TITLE
Warn users about overly generous github permissions

### ISSUE THREAD

**Issue by prabhu** [owasp-dep-scan/dep-scan#100]
A number of users of AppThreat pass the default GITHUB_TOKEN with overly generous read/write permissions across their repos and packages. It would be nice to detect this and flag up a warning.

**Comment by timmyteo** [comment]
@prabhu This appears to be possible for the classic GitHub Personal Access Tokens but not for the new Beta Fine Grained tokens. We would have to make a call to the GitHub API using the supplied token in order to view the permissions on the token. Is this acceptable? https://github.com/orgs/community/discussions/25259

**Comment by prabhu** [comment]
@timmyteo, this sounds like a good approach. If you're willing to contribute, you can add a github client library and a new github.py file so that we can add things like pull-request annotation/commenting, etc. in the future.

**Comment by timmyteo** [comment]
Sounds good @prabhu, I will start working on this. It looks like the PAT only needs a scope of [read:packages](https://github.com/owasp-dep-scan/dep-scan#github-security-advisory). I'll add a WARNING log entry for any PAT that has scopes beyond what is necessary for dep-scan, recommending the user to utilize a token with only the necessary scope.

**Comment by timmyteo** [comment]
Hi @prabhu - FYI this feature is included in [Release 4.3.3](https://github.com/owasp-dep-scan/dep-scan/releases/tag/v4.3.3)
