### ISSUE TITLE
Download pre-built vdb using oras

### ISSUE THREAD

**Issue by prabhu** [owasp-dep-scan/dep-scan#111]
My previous attempt to use oras-py didn't work very well. Hoping the project has improved and become stable by now.

https://github.com/oras-project/oras-py

We currently have vdb on ghcr under the following namespace. We can optionally support specifying multiple registries since we all know about GitHub. AWS ECR Public was added to vdb with this [PR](https://github.com/AppThreat/vdb/pull/6)

```
public.ecr.aws/appthreat/vdb:v5
ghcr.io/appthreat/vdb:v5
```

The configuration file could be designed together with #110

**Comment by saketjajoo** [comment]
Currently, the oras-py library has a bug (https://github.com/oras-project/oras-py/issues/100) where it pulls an image into `PATH/sub_dir/sub_dir/` instead of `PATH/sub_dir/`. I have submitted a PR (https://github.com/oras-project/oras-py/pull/106) to fix it. Once the PR gets approved, we can work on this issue to use the latest oras-py library to download the pre-built vdb image.

A short-term fix could be to pin the oras-py version to the current one (0.1.23), pull the image using the library, and then manually moving the image to its parent directory before removing the child subdirectory.

**Comment by saketjajoo** [comment]
PR to fix this: https://github.com/owasp-dep-scan/dep-scan/pull/128.

**Comment by saketjajoo** [comment]
Fixed!
